[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000"
